USE [master]
GO
IF EXISTS(SELECT * FROM sysdatabases WHERE NAME='HotelDB')
DROP DATABASE HotelDB
GO
/****** Object:  Database [HotelDB]    Script Date: 2018/4/23 ÷‹“ª 16:18:56 ******/
CREATE DATABASE [HotelDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelDB', FILENAME = N'C:\DATA\HotelDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HotelDB_log', FILENAME = N'C:\DATA\HotelDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HotelDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HotelDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HotelDB] SET  MULTI_USER 
GO

ALTER DATABASE [HotelDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HotelDB] SET  READ_WRITE 
GO


